config/routes.rb
Rails.application.routes.draw do

  get 'parametres/edit'
  post 'parametres/update'

  get 'questions/conjugaison'
  post 'questions/verification'
  get 'questions/vocabulaire'
  get 'questions', to: 'questions#lance', as: 'lance_questions'

  resources :vocabulaires
  get 'vocabulaire/sauve', to: 'vocabulaires#sauve', as: 'sauve_vocabulaire'

  devise_for :users
  resources :conjugaisons
  get '/conjugaisons/:id/copie', to: 'conjugaisons#copie', as: 'copie_conjugaison'
  get 'conjugaisons/sauve', to: 'conjugaisons#sauve', as: 'sauve_conjugaison'
  get 'conjugaisons/aligne', to: 'conjugaisons#aligne', as: 'aligne_conjugaison'

root 'conjugaisons#index'

end

app/models/vocabulaire.rb
class Vocabulaire < ActiveRecord::Base

  paginates_per 40

  MAX_ESSAIS = 16
  SUCCES = 0.5
  ECHEC = 2

  validates :mot_directeur, presence: {message: 'Le mot directeur est obligatoire'}
  validates :francais, presence: {message: 'Le mot ou expression en français est obligatoire'}
  validates :italien, presence: {message: 'La traduction italienne est obligatoire'}
  validates :compteur, numericality: { greater_than: 0, message: 'Le compteur doit être un entier positif' }

  def self.aleatoire(compteur_min, date_min)
    (rand * Vocabulaire.where("created_at >= ? and compteur >= ?",\
      date_min,compteur_min).sum('compteur')).ceil
  end

  def self.deux_colonnes(vocabulaires)
    i = 0
    liste = []
    vocabulaires.each do |v|
      if i< Vocabulaire.default_per_page/2
        liste[i] = {gauche: v}
      else
        liste[i-Vocabulaire.default_per_page/2][:droite] = v
      end
      i += 1
    end
    liste
  end

  def self.question(id)
    @vocabulaire = Vocabulaire.find(id)
  end

  def self.tirage(num,compteur_min, date_min)
    @dico = Vocabulaire.where("created_at >= ? and compteur >= ?",\
      date_min,compteur_min).order(:mot_directeur, :francais)
    @dico.each do |mot|
      if mot.compteur >= num
        return mot
      else
        num -= mot.compteur
      end
    end
    return false
  end

  def score(ok,inutile)
    if ok
      facteur = Vocabulaire::SUCCES
    else
      facteur = Vocabulaire::ECHEC
      Erreur.create(code: 'vocabulaire', ref: id) unless Erreur.where(ref: id).first
    end
    if (self.compteur * facteur).round >= 1
      self.compteur = (self.compteur * facteur).round
    else
      self.compteur = 1
    end
    self
  end

  def self.sauve
#['papier','les papiers (état civil)',8,'i documenti']
    liste = File.new('db/mots/liste_mots.txt',mode='w')
    Vocabulaire.all.order(:mot_directeur).each do |v|
      IO.write(liste,\
        "[\""+v.mot_directeur.to_str+"\",\""+v.francais+"\",8,\""+v.italien+"\"],\n",liste.size)
    end
  end

end

app/controllers/vocabulaires_controller.rb
class VocabulairesController < ApplicationController

  before_action :set_vocabulaire, only: [:show, :edit, :update, :destroy]
  before_action :set_session, only: [:index]
  unless Rails.env.test?
    before_action :authenticate_user!, only: [:new, :edit, :update, :destroy]
    before_action :verifie_utilisateur, only: [:new, :edit, :update, :destroy]
  end

  # GET /vocabulaires
  # GET /vocabulaires.json
  def index
    session[:page] = (params[:page] ||= session[:page])
    @vocabulaires = Vocabulaire.where("created_at >= ? and compteur >= ?",\
      session[:voc_date_min],session[:voc_compteur_min]).order(:mot_directeur).page params[:page]
  end

  # GET /vocabulaires/1
  # GET /vocabulaires/1.json
  def show
  end

  # GET /vocabulaires/new
  def new
    @vocabulaire = Vocabulaire.new
  end

  # GET /vocabulaires/1/edit
  def edit
  end

  # POST /vocabulaires
  # POST /vocabulaires.json
  def create
    @vocabulaire = Vocabulaire.new(vocabulaire_params)

    respond_to do |format|
      if @vocabulaire.save
        format.html { redirect_to @vocabulaire, notice: 'Vocabulaire was successfully created.' }
        format.json { render action: 'show', status: :created, location: @vocabulaire }
      else
        format.html { render action: 'new' }
        format.json { render json: @vocabulaire.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vocabulaires/1
  # PATCH/PUT /vocabulaires/1.json
  def update
    respond_to do |format|
      if @vocabulaire.update(vocabulaire_params)
        format.html { redirect_to @vocabulaire, notice: 'Vocabulaire was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @vocabulaire.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vocabulaires/1
  # DELETE /vocabulaires/1.json
  def destroy
    @vocabulaire.destroy
    respond_to do |format|
      format.html { redirect_to vocabulaires_url }
      format.json { head :no_content }
    end
  end

  # GET/vocabulaires/sauve
  def sauve
    unless Rails.env.production?
      Vocabulaire.sauve
    end
    redirect_to :action => 'index'
  end


  private

    def set_session
      session[:voc_compteur_min] ||= 0
      session[:voc_date_min] ||= Vocabulaire.minimum('created_at').to_s
#      session[:conj_compteur_min] ||= 0
#      session[:conj_date_min] ||= Conjugaison.minimum('created_at').to_s
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_vocabulaire
      @vocabulaire = Vocabulaire.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vocabulaire_params
      params.require(:vocabulaire).permit(:mot_directeur, :compteur, :francais, :italien)
    end

    def verifie_utilisateur
      unless current_user.email == 'jacques.marzin@free.fr'
        redirect_to :action => 'index'
      end
    end

end

app/helpers/vocabulaires_helper.rb
module VocabulairesHelper
end

app/views/vocabulaires/_form.html.haml
-@vocabulaire.compteur = Vocabulaire::MAX_ESSAIS unless @vocabulaire.compteur
= form_for @vocabulaire do |f|
  - if @vocabulaire.errors.any?
    #error_explanation
      %h2= "#{pluralize(@vocabulaire.errors.count, "erreur")}. Le mot ou l'expression n'a pas été sauvegardé."
      %ul
        - @vocabulaire.errors.full_messages.each do |msg|
          %li= msg
  %br
  .field
    = f.label :mot_directeur
    = f.text_field :mot_directeur, autofocus: true
  .field
    = f.label :francais
    = f.text_field :francais
  .field
    = f.label :compteur
    = f.number_field :compteur
  .field
    = f.label :italien
    = f.text_field :italien

  .actions
    = f.submit 'Enregistrer'

app/views/vocabulaires/edit.html.haml
%h1 Correction d'un mot ou d'une expression

= render 'form'

= link_to 'Voir', @vocabulaire
\|
= link_to 'Retour', vocabulaires_path

app/views/vocabulaires/index.html.haml
%h1 Liste des mots ou expression

%table
  %tr
    - (1..2).each_with_index do |i|
      %th Mot directeur
      %th Francais
      %th Compteur
      %th Italien
      %th
      %th
      %th
      -if i == 1
        %th#separateur

  - liste = Vocabulaire.deux_colonnes(@vocabulaires)
  - liste.each do |item|
    %tr
      %td= item[:gauche].mot_directeur
      %td= if item[:gauche].francais.length > 25 then item[:gauche].francais[0..21]+'...' else item[:gauche].francais end
      %td= item[:gauche].compteur
      %td= if item[:gauche].italien.length > 25 then item[:gauche].italien[0..21]+'...' else item[:gauche].italien end
      %td= link_to 'Voir', item[:gauche]
      %td= link_to 'Corriger', edit_vocabulaire_path(item[:gauche])
      %td= link_to 'Supprimer', item[:gauche], :method => :delete, :data => { :confirm => 'Are you sure?' }
      -if item.has_key?(:droite)
        %td#separateur
        %td= item[:droite].mot_directeur
        %td= if item[:droite].francais.length > 25 then item[:droite].francais[0..21]+'...' else item[:droite].francais end
        %td= item[:droite].compteur
        %td= if item[:droite].italien.length > 25 then item[:droite].italien[0..21]+'...' else item[:droite].italien end
        %td= link_to 'Voir', item[:droite]
        %td= link_to 'Corriger', edit_vocabulaire_path(item[:droite])
        %td= link_to 'Supprimer', item[:droite], :method => :delete, :data => { :confirm => 'Are you sure?' }

%br
= paginate @vocabulaires
= link_to 'Nouveau mot ou expression', new_vocabulaire_path

app/views/vocabulaires/new.html.haml
%h1 Nouveau mot ou expression

= render 'form'

= link_to 'Retour', vocabulaires_path

app/views/vocabulaires/show.html.haml
%p#notice= notice

%p
  %b Mot_directeur:
  = @vocabulaire.mot_directeur
%p
  %b Francais:
  = @vocabulaire.francais
%p
  %b Compteur:
  = @vocabulaire.compteur
%p
  %b Italien:
  = @vocabulaire.italien

= link_to 'Corriger', edit_vocabulaire_path(@vocabulaire)
\|
= link_to 'Nouveau mot ou expression', new_vocabulaire_path
\|
= link_to 'Retour', vocabulaires_path