config/routes.rb
Rails.application.routes.draw do

  get 'parametres/edit'
  post 'parametres/update'

  get 'questions/conjugaison'
  post 'questions/verification'
  get 'questions/vocabulaire'
  get 'questions', to: 'questions#lance', as: 'lance_questions'

  resources :vocabulaires
  get 'vocabulaire/sauve', to: 'vocabulaires#sauve', as: 'sauve_vocabulaire'

  devise_for :users
  resources :conjugaisons
  get '/conjugaisons/:id/copie', to: 'conjugaisons#copie', as: 'copie_conjugaison'
  get 'conjugaisons/sauve', to: 'conjugaisons#sauve', as: 'sauve_conjugaison'
  get 'conjugaisons/aligne', to: 'conjugaisons#aligne', as: 'aligne_conjugaison'

root 'conjugaisons#index'

end

app/models/conjugaison.rb
class Temps

  attr_accessor :radical, :voyelle_thematique, :personnes

  def initialize(tableau)
    @radical = tableau[0]
    @voyelle_thematique = tableau[1]
    @personnes = tableau.drop(2)
  end

  def s1
    (personnes[0] == '---') ? @personnes[0] : @radical+@voyelle_thematique+@personnes[0]
  end

  def s2
    (personnes[1] == '---') ? @personnes[1] : @radical+@voyelle_thematique+@personnes[1]
  end

  def s3
    (personnes[2] == '---') ? @personnes[2] : @radical+@voyelle_thematique+@personnes[2]
  end

  def p1
    (personnes[3] == '---') ? @personnes[3] : @radical+@voyelle_thematique+@personnes[3]
  end

  def p2
    (personnes[4] == '---') ? @personnes[4] : @radical+@voyelle_thematique+@personnes[4]
  end

  def p3
    (personnes[5] == '---') ? @personnes[5] : @radical+@voyelle_thematique+@personnes[5]
  end

  def to_s
    s1+' '+s2+' '+s3+' '+p1+' '+p2+' '+p3
  end

end

class Mode

  def initialize(tableau)
    @mode = []
    tableau.each {|el| @mode << el}
  end

  def pres
    @mode[0]
  end

  def imp
    @mode[1]
  end

  def parf
    @mode[2]
  end

  def fut
    @mode[3]
  end

end


class Conjugaison < ActiveRecord::Base

  MAX_ESSAIS = 16
  SUCCES = 0.5
  ECHEC = 2

  validates :infinitif, presence: {message: "L'infinitif est obligatoire"}
  validates :verbe, presence: {message: "Le détail de la conjugaison est obligatoire"}
  validates :infinitif, uniqueness: {message: "L'infinitif doit être unique"}

  before_save :ser_verbe
  after_save :deser_verbe
  after_find :deser_verbe

  def maj(conjugaison_params, params)
    total_essais = 0
    params['formes'].each_with_index do |f, i|
      if f == '---'
        params['compteurs'][i] = 0
      else
        params['compteurs'][i] = params['compteurs'][i].to_i
        total_essais += params['compteurs'][i]
      end
    end
    t1 = [self.infinitif,'']
    t1 << params['formes'][49]
    t1 << params['formes'][48]
    pres = [params['ind']['pres']['radical']]
    pres << params['ind']['pres']['voyelle_thematique']
    pres += params['formes'][0..5]
    imp = [params['ind']['imp']['radical']]
    imp << params['ind']['imp']['voyelle_thematique']
    imp += params['formes'][6..11]
    parf = [params['ind']['parf']['radical']]
    parf << params['ind']['parf']['voyelle_thematique']
    parf += params['formes'][12..17]
    fut = [params['ind']['fut']['radical']]
    fut << params['ind']['fut']['voyelle_thematique']
    fut += params['formes'][18..23]
    t1 << Mode.new([Temps.new(pres),Temps.new(imp),Temps.new(parf),Temps.new(fut)])
    pres = [params['sub']['pres']['radical']]
    pres << params['sub']['pres']['voyelle_thematique']
    pres += params['formes'][24..29]
    imp = [params['sub']['imp']['radical']]
    imp << params['sub']['imp']['voyelle_thematique']
    imp += params['formes'][30..35]
    t1 << Mode.new([Temps.new(pres),Temps.new(imp)])
    pres = [params['cond']['pres']['radical']]
    pres << params['cond']['pres']['voyelle_thematique']
    pres += params['formes'][42..47]
    t1 << Mode.new([Temps.new(pres)])
    pres = [params['imp']['radical']]
    pres << params['imp']['voyelle_thematique']
    pres += params['formes'][36..41]
    t1 << Temps.new(pres)

    conjugaison_params['essais_verbe'] = total_essais
    conjugaison_params['verbe'] = Verbe.new({conj: t1,compteurs: params['compteurs']})
    self.update(conjugaison_params)
  end

  def self.aleatoire(compteur_min,date_min)
    (rand * Conjugaison.where("created_at >= ? and essais_verbe >= ?",\
      date_min,compteur_min).sum("essais_verbe")).ceil
  end

  def self.question(id, forme)
    @conjugaison = Conjugaison.find(id)
    { forme: forme, texte: @conjugaison.verbe.show(forme),\
      attendu: eval("@conjugaison.verbe.#{forme}"),\
      conjugaison: @conjugaison,\
      rang: Verbe::FORMES.find_index(forme)+1}
  end

  def tirage(num)
    i=0
    while num > verbe.compteurs[i] do
      num -= verbe.compteurs[i]
      i += 1
      return false if i == Verbe::FORMES.size
    end
    {forme: Verbe::FORMES[i],texte: verbe.show(Verbe::FORMES[i]),\
      attendu: eval("verbe.#{Verbe::FORMES[i]}")}
  end

  def self.tirage(num,compteur_min,date_min)
    @conjugaisons = Conjugaison.where("created_at >= ? and essais_verbe >= ?",\
      date_min,compteur_min).order(:id)
    i = num
    @conjugaisons.each do |c|
      return {conjugaison: c, rang: i}.merge(c.tirage(i)) if c.essais_verbe >= i
      i -= c.essais_verbe
    end
    return false
  end

  def self.accepte?(reponse, attendu)
    return false if reponse == ''
    reponses = reponse.downcase.strip.split('/')
    attendus = attendu.downcase.strip.split('/')
    resultat = true
    reponses.each do |rep|
      resultat = resultat && attendus.include?(rep)
    end
    resultat
  end

  def score(ok,forme)
    if ok
      facteur = Conjugaison::SUCCES
    else
      facteur = Conjugaison::ECHEC
      Erreur.create(code: 'conjugaison',ref: id, forme: forme) unless Erreur.where(ref: id, forme: forme).first
    end
    self.essais_verbe -= verbe.compteurs[Verbe.rang_forme(forme)]
    if (verbe.compteurs[Verbe.rang_forme(forme)] * facteur).round >= 1
      verbe.compteurs[Verbe.rang_forme(forme)] = \
        (verbe.compteurs[Verbe.rang_forme(forme)]* facteur).round
    else
      verbe.compteurs[Verbe.rang_forme(forme)] = 1
    end
    self.essais_verbe += verbe.compteurs[Verbe.rang_forme(forme)]
    self
  end

  def self.duree(heure_debut)
    duree = Time.at(Time.now - heure_debut)
    texte = ''
    if duree.hour > 1
      texte += "#{duree.hour - 1} h "
    end
    if duree.min > 0
      texte += "#{duree.min} min "
    end
    if duree.sec > 0
      texte += "#{duree.sec} sec"
    end
    texte
  end

  def self.stats(bonnes, mauvaises)
    texte = ''
    if bonnes+mauvaises > 0
      if bonnes + mauvaises > 1
        texte += "#{bonnes + mauvaises} questions, "
      else
        texte += "1 question, "
      end
      texte += "#{(bonnes*100/(bonnes + mauvaises)).ceil} % de réussite"
    end
    texte
  end

  def self.sauve
    liste = File.new('db/verbes/liste_verbes.txt',mode='w')
    Conjugaison.order(:id).each do |c|
      IO.write(liste,c.infinitif+"\n"+c.essais_verbe.to_s+"\n",liste.size)
      IO.write('db/verbes/'+c.infinitif+'.yml',YAML.dump(c.verbe))
    end
    return true
  end

  def self.aligne(matrice)
    @matrice = Conjugaison.where(infinitif: matrice).take
    Conjugaison.all.each do |conj|
      if conj.infinitif != matrice
        conj.essais_verbe = 0
        conj.verbe.compteurs.each_index do |i|
          if conj.verbe.compteurs[i] > 0
            conj.verbe.compteurs[i] = @matrice.verbe.compteurs[i]
            conj.essais_verbe += conj.verbe.compteurs[i]
          end
        end
      end
      conj.save!
    end
  end

  protected

  def ser_verbe
    if self.verbe.class == Verbe
      self.verbe = YAML.dump(self.verbe)
    end
  end

  def deser_verbe
    begin
      self.verbe = YAML.load(self.verbe)
    rescue
    end
  end

end

app/controllers/conjugaisons_controller.rb
class ConjugaisonsController < ApplicationController
  before_action :set_conjugaison, only: [:show, :edit, :update, :destroy, :copie]
  before_action :set_session, only: [:index]
  unless Rails.env.test?
    before_action :authenticate_user!, only: [:new, :edit, :update, :destroy, :copie]
    before_action :verifie_utilisateur, only: [:new, :edit, :update, :destroy, :copie]
  end

  # GET /conjugaisons
  # GET /conjugaisons.json
  def index
    @conjugaisons = Conjugaison.where("created_at >= ? and essais_verbe >= ?",\
      session[:conj_date_min],session[:conj_compteur_min]).order(:id)
  end

  # GET /conjugaisons/1
  # GET /conjugaisons/1.json
  def show
  end

  # GET /conjugaisons/new
  def new
    @conjugaison = Conjugaison.new(infinitif: '',\
      essais_verbe: Verbe::FORMES.size * Conjugaison::MAX_ESSAIS, verbe: Verbe.new(''))
  end


  # GET/conjugaison/1/copie
  def copie
    @copie = Conjugaison.new(\
      infinitif: 'Copie de ' + @conjugaison.infinitif,\
       essais_verbe: @conjugaison.essais_verbe,\
       verbe: @conjugaison.verbe)
    @copie.save
    redirect_to :action => 'edit', :id => @copie.id
  end

  # GET/conjugaisons/sauve
  def sauve
    unless Rails.env.production?
      Conjugaison.sauve
    end
    redirect_to :action => 'index'
  end

  #GET/conjugaisons/aligne
  def aligne
    Conjugaison.aligne('avere')
    redirect_to :action => 'index'
  end

  # GET /conjugaisons/1/edit
  def edit
  end

  # POST /conjugaisons
  # POST /conjugaisons.json
  def create
    @conjugaison = Conjugaison.new(conjugaison_params)

    respond_to do |format|
      if @conjugaison.maj(conjugaison_params, params)
        format.html { redirect_to @conjugaison, notice: 'Conjugaison was successfully created.' }
        format.json { render action: 'show', status: :created, location: @conjugaison }
      else
        format.html { render action: 'new' }
        format.json { render json: @conjugaison.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /conjugaisons/1
  # PATCH/PUT /conjugaisons/1.json
  def update
    respond_to do |format|
      if @conjugaison.maj(conjugaison_params, params)
        format.html { redirect_to @conjugaison, notice: 'La conjugaison a bien été mise à jour.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @conjugaison.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /conjugaisons/1
  # DELETE /conjugaisons/1.json
  def destroy
    @conjugaison.destroy
    respond_to do |format|
      format.html { redirect_to conjugaisons_url }
      format.json { head :no_content }
    end
  end

  private
    def set_session
#      session[:voc_compteur_min] ||= 0
#      session[:voc_date_min] ||= Vocabulaire.minimum('created_at').to_s
      session[:conj_compteur_min] ||= 0
      session[:conj_date_min] ||= Conjugaison.minimum('created_at').to_s
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_conjugaison
      @conjugaison = Conjugaison.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def conjugaison_params
      params.require(:conjugaison).permit(:infinitif, :essais_verbe, :verbe)
    end

    def verifie_utilisateur
      unless current_user.email == 'jacques.marzin@free.fr'
        redirect_to :action => 'index'
      end
    end

end

app/helpers/conjugaisons_helper.rb
module ConjugaisonsHelper
end

app/views/conjugaisons/_form.html.haml
= form_for @conjugaison do |f|
  - if @conjugaison.errors.any?
    #error_explanation
      %h2= "#{pluralize(@conjugaison.errors.count, "error")} prohibited this conjugaison from being saved:"
      %ul
        - @conjugaison.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :infinitif, size: 20
    = f.text_field :infinitif
  .field
    = f.label :essais
    = f.number_field :essais_verbe

  %br
  %table#saisie
    %tr
      %th Mode
      %th Temps
      %th Radical
      %th Voyelle
      %th s1
      %th s2
      %th s3
      %th p1
      %th p2
      %th p3
    %tr
      %td Indicatif
      %td Présent
      %td=text_field_tag('ind[pres][radical]', value = @conjugaison.verbe.ind.pres.radical,options={size: 10})
      %td=text_field_tag('ind[pres][voyelle_thematique]', value = @conjugaison.verbe.ind.pres.voyelle_thematique, options={size: 1})
      - (0..5).each do |i|
        %td=text_field_tag('formes[]', value = @conjugaison.verbe.ind.pres.personnes[i], options={size: 10})
    %tr
      %td Essais
      %td
      %td
      %td
      - (0..5).each do |i|
        %td=text_field_tag('compteurs[]', value = @conjugaison.verbe.compteurs[i], options={size: 2})
    %tr
      %td Indicatif
      %td Imparfait
      %td=text_field_tag('ind[imp][radical]', value = @conjugaison.verbe.ind.imp.radical,options={size: 10})
      %td=text_field_tag('ind[imp][voyelle_thematique]', value = @conjugaison.verbe.ind.imp.voyelle_thematique, options={size: 1})
      - (0..5).each do |i|
        %td=text_field_tag('formes[]', value = @conjugaison.verbe.ind.imp.personnes[i], options={size: 10})
    %tr
      %td Essais
      %td
      %td
      %td
      - (6..11).each do |i|
        %td=text_field_tag('compteurs[]', value = @conjugaison.verbe.compteurs[i], options={size: 2})
    %tr
      %td Indicatif
      %td Parfait
      %td=text_field_tag('ind[parf][radical]', value = @conjugaison.verbe.ind.parf.radical,options={size: 10})
      %td=text_field_tag('ind[parf][voyelle_thematique]', value = @conjugaison.verbe.ind.parf.voyelle_thematique, options={size: 1})
      - (0..5).each do |i|
        %td=text_field_tag('formes[]', value = @conjugaison.verbe.ind.parf.personnes[i], options={size: 10})
    %tr
      %td Essais
      %td
      %td
      %td
      - (12..17).each do |i|
        %td=text_field_tag('compteurs[]', value = @conjugaison.verbe.compteurs[i], options={size: 2})
    %tr
      %td Indicatif
      %td Futur
      %td=text_field_tag('ind[fut][radical]', value = @conjugaison.verbe.ind.fut.radical,options={size: 10})
      %td=text_field_tag('ind[fut][voyelle_thematique]', value = @conjugaison.verbe.ind.fut.voyelle_thematique, options={size: 1})
      - (0..5).each do |i|
        %td=text_field_tag('formes[]', value = @conjugaison.verbe.ind.fut.personnes[i], options={size: 10})
    %tr
      %td Essais
      %td
      %td
      %td
      - (18..23).each do |i|
        %td=text_field_tag('compteurs[]', value = @conjugaison.verbe.compteurs[i], options={size: 2})
    %tr
      %td Subjonctif
      %td Présent
      %td=text_field_tag('sub[pres][radical]', value = @conjugaison.verbe.sub.pres.radical,options={size: 10})
      %td=text_field_tag('sub[pres][voyelle_thematique]', value = @conjugaison.verbe.sub.pres.voyelle_thematique, options={size: 1})
      - (0..5).each do |i|
        %td=text_field_tag('formes[]', value = @conjugaison.verbe.sub.pres.personnes[i], options={size: 10})
    %tr
      %td Essais
      %td
      %td
      %td
      - (24..29).each do |i|
        %td=text_field_tag('compteurs[]', value = @conjugaison.verbe.compteurs[i], options={size: 2})
    %tr
      %td Subjonctif
      %td Imparfait
      %td=text_field_tag('sub[imp][radical]', value = @conjugaison.verbe.sub.imp.radical,options={size: 10})
      %td=text_field_tag('sub[imp][voyelle_thematique]', value = @conjugaison.verbe.sub.imp.voyelle_thematique, options={size: 1})
      - (0..5).each do |i|
        %td=text_field_tag('formes[]', value = @conjugaison.verbe.sub.imp.personnes[i], options={size: 10})
    %tr
      %td Essais
      %td
      %td
      %td
      - (30..35).each do |i|
        %td=text_field_tag('compteurs[]', value = @conjugaison.verbe.compteurs[i], options={size: 2})
    %tr
      %td{:colspan => 2} Impératif
      %td=text_field_tag('imp[radical]', value = @conjugaison.verbe.imp.radical,options={size: 10})
      %td=text_field_tag('imp[voyelle_thematique]', value = @conjugaison.verbe.imp.voyelle_thematique, options={size: 1})
      - (0..5).each do |i|
        %td=text_field_tag('formes[]', value = @conjugaison.verbe.imp.personnes[i], options={size: 10})
    %tr
      %td Essais
      %td
      %td
      %td
      - (36..41).each do |i|
        %td=text_field_tag('compteurs[]', value = @conjugaison.verbe.compteurs[i], options={size: 2})
    %tr
      %td Conditionnel
      %td Présent
      %td=text_field_tag('cond[pres][radical]', value = @conjugaison.verbe.cond.pres.radical,options={size: 10})
      %td=text_field_tag('cond[pres][voyelle_thematique]', value = @conjugaison.verbe.cond.pres.voyelle_thematique, options={size: 1})
      - (0..5).each do |i|
        %td=text_field_tag('formes[]', value = @conjugaison.verbe.cond.pres.personnes[i], options={size: 10})
    %tr
      %td Essais
      %td
      %td
      %td
      - (42..47).each do |i|
        %td=text_field_tag('compteurs[]', value = @conjugaison.verbe.compteurs[i], options={size: 2})
    %tr
      %td{:colspan => 2} Gérondif
      %td{:colspan => 6}=text_field_tag('formes[]', value = @conjugaison.verbe.ger,options={size: 10})
    %tr
      %td Essais
      %td
      %td=text_field_tag('compteurs[]', value = @conjugaison.verbe.compteurs[48], options={size: 2})
    %tr
      %td{:colspan => 2} Participe passé
      %td{:colspan => 6}=text_field_tag('formes[]', value = @conjugaison.verbe.ppass, options={size: 10})
    %tr
      %td Essais
      %td
      %td=text_field_tag('compteurs[]', value = @conjugaison.verbe.compteurs[49], options={size: 2})

  .actions
    = f.submit 'Enregistrer'

app/views/conjugaisons/edit.html.haml
%h1 Modification d'une conjugaison

= render 'form'

= link_to 'Voir', @conjugaison
\|
= link_to 'Retour', conjugaisons_path

app/views/conjugaisons/index.html.haml
%h1 Liste des verbes connus

%table
  %tr
    %th Infinitif
    %th Essais
    %th
    %th
    %th

  - @conjugaisons.each do |conjugaison|
    %tr
      %td= conjugaison.infinitif
      %td= conjugaison.essais_verbe
      %td= link_to 'Voir', conjugaison
      %td= link_to 'Corriger', edit_conjugaison_path(conjugaison)
      %td= link_to 'Copier', copie_conjugaison_path(conjugaison)
      %td= link_to 'Supprimer', conjugaison, :method => :delete, :data => { :confirm => 'Êtes-vous sûr ?' }

%br
= link_to 'Nouvelle Conjugaison', new_conjugaison_path

app/views/conjugaisons/new.html.haml
%h1 Nouvelle conjugaison

= render 'form'

= link_to 'Retour', conjugaisons_path

app/views/conjugaisons/show.html.haml
%p#notice= notice

%p
  %b Infinitif:
  = @conjugaison.infinitif
%p
  %b Essais:
  = @conjugaison.essais_verbe

%table#verbe1
  -tab_temps=['ind.pres.','ind.imp.','ind.parf.','ind.fut.']
  -tab_personnes=['s1','s2','s3','p1','p2','p3']
  %tr
    %th#mode
    %th PRESENT
    %th IMPARFAIT
    %th PARFAIT
    %th FUTUR
  -tab_personnes.each do |personne|
    %tr
      -if personne == 's1'
        %td#gras{:rowspan => 6} INDICATIF
      -tab_temps.each do |temps|
        %td=@conjugaison.verbe.show(temps+personne)

%table#verbe2
  -tab_temps=['sub.pres.','sub.imp.','imp.','cond.pres.']
  %tr
    %th#mode
    %th PRESENT
    %th IMPARFAIT
    %th IMPERATIF
    %th CONDITIONNEL
  -tab_personnes.each do |personne|
    %tr
      -if personne == 's1'
        %td#gras{:rowspan => 6} SUBJONCTIF
      -tab_temps.each do |temps|
        %td=@conjugaison.verbe.show(temps+personne)

%table#verbe3
  %tr
    %th GERONDIF
    %th PARTICIPE PASSE

  %tr
    %td=@conjugaison.verbe.show('ger')
    %td=@conjugaison.verbe.show('ppass')
= link_to 'Corriger', edit_conjugaison_path(@conjugaison)
\|
= link_to 'Retour', conjugaisons_path