config/routes.rb
Rails.application.routes.draw do

  get 'parametres/edit'
  post 'parametres/update'

  get 'questions/conjugaison'
  post 'questions/verification'
  get 'questions/vocabulaire'
  get 'questions', to: 'questions#lance', as: 'lance_questions'

  resources :vocabulaires
  get 'vocabulaire/sauve', to: 'vocabulaires#sauve', as: 'sauve_vocabulaire'

  devise_for :users
  resources :conjugaisons
  get '/conjugaisons/:id/copie', to: 'conjugaisons#copie', as: 'copie_conjugaison'
  get 'conjugaisons/sauve', to: 'conjugaisons#sauve', as: 'sauve_conjugaison'
  get 'conjugaisons/aligne', to: 'conjugaisons#aligne', as: 'aligne_conjugaison'

root 'conjugaisons#index'

end

app/views/layouts/_header.html.haml
%header#page_header
  %table
    %th=link_to 'Vocabulaire', vocabulaires_path \
    %th=link_to 'Conjugaison', conjugaisons_path \
    %th=link_to 'Révision', lance_questions_path \
    %th=link_to 'Révision du vocabulaire', questions_vocabulaire_path \
    %th=link_to 'Révision des conjugaisons', questions_conjugaison_path \
    %th=link_to 'Paramétrage', parametres_edit_path
  %hr

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Conjuguer</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>

  <%= yield %>

</body>
</html>